### ISSUE TITLE
Add support for zstd compression

### ISSUE THREAD

**Issue by tych0** [opencontainers/umoci#316]
Per https://github.com/opencontainers/image-spec/issues/803 using zstd compression seems to be on peoples minds.

After reading about it, it seems it's been designed with parallelism in mind, among just being faster on a single core as well. I think it would definitely speed up some of our use cases, at least.

**Comment by tych0** [comment]
Just looking at the API, it seems like it would only take a relatively small number of changes to Mutator and the unpacking code.

**Comment by nishakm** [comment]
Can I try to submit a PR for this?

**Comment by tych0** [comment]
On Thu, Nov 12, 2020 at 10:56:02AM -0800, Nisha K wrote:
> Can I try to submit a PR for this?

Sure, that would be great! I think I already did some of the mutator
work with the Compressor interface (but I didn't actually implement a
zst Compressor). It also looks like gzip is hard coded in a few other
places that will need to be abstracted somehow.
