### ISSUE TITLE
ci: migrate away from Travis

### ISSUE THREAD

**Issue by cyphar** [opencontainers/umoci#353]
Turns out travis is going to be non-free for FOSS projects so we're going to need to switch to GitHub Actions after all. Luckily we already have caching set up in a way we can fairly easily port it to GH Actions.

**Comment by cyphar** [comment]
And now Docker Hub's new limits are triggering issues when trying to pull `opensuse/leap:latest`. What a pain.

**Comment by vrothberg** [comment]
Random drive-by comment.  I found GitHub Actions very hard to approach and maintain.  In case you feel the same way, https://cirrus-ci.org may be an alternative.

**Comment by cyphar** [comment]
Yeah I had issues with my first attempt at using GH Actions and I did look at cirrus-ci at the time. I'll take another look at it. Thanks @vrothberg. :smiley_cat:

**Comment by cyphar** [comment]
And if we do this we can remove codecov because it seems to be quite useless recently.

**Comment by cyphar** [comment]
This is now more pressing, since Travis has ramped up their deprecation timeline and since all the maintainers are employed we don't qualify for their "open source" plans.

**Comment by cyphar** [comment]
7091cd1e1154711941c66f91f1253a26089b2eee
