### ISSUE TITLE
Unix-style interoperability with oras?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/umoci#355]
Is there some feature(s) or redesign to make these tools interoperable using Unix pipes?

For example, to push:
```
umoci export myimage:mytag | oras push
```

and to pull:
```
oras pull myimage:mytag | umoci import
```

**Comment by jdolitsky** [comment]
See also https://github.com/deislabs/oras/issues/213

**Comment by cyphar** [comment]
What would the contents of the pipe look like? A generated `.tar.gz` of the OCI image blobs? I don't think that's really necessary -- all that's really necessary for ORAS and umoci to be interoperable is that ORAS have a built-in mode for interacting with OCI image layouts, which is just a directory of the form:

```
% skopeo copy docker://busybox:latest oci:busybox:latest
% tree busybox
busybox
├── blobs
│   └── sha256
│       ├── 13681b59908f5850f8965cb7fa8e843a78b59ae634c127e4b20c11a50b7af1c0
│       ├── 4bccc944af45654d847efecb82d396ab0831377f0297ff53fad085d67a91d9ef
│       └── e5d9363303ddee1686b203170d78283404e46a742d4c62ac251aae5acbda8df8
├── index.json
└── oci-layout
```

Last I looked, ORAS does support this in its library so maybe the only thing missing is a CLI UX for interacting with such layouts.

**Comment by jdolitsky** [comment]
Understood. When umoci runs the `unpack` routine, is it pointing at a centralized cache containing `index.json` and `blobs`? If thats the case, we would just need to add an `index.json` to the oras cache, containing reference to `busybox:latest`. 

Regarding pipes, I get that passing the whole tar.gz as stdin is overkill. Perhaps we have some shared JSON format that is passed between tools that simply references something in a cache?

Example: `{"image": "docker.io/busybox:latest", "cas": "/users/jim/.oci"}`

**Comment by cyphar** [comment]
@jdolitsky 

> is it pointing at a centralized cache containing index.json and blobs

Actually the `--image <path>:<tag>` cmdline indicates the cache  with `<path>` (and `<tag>` is the `org.opencontainers.ref.name` to look up in `index.json`). Though there were discussions some time ago about having a centralised cache backup but this is strictly more flexible.
