### ISSUE TITLE
Tag a new release with FreeBSD support

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [opencontainers/umoci#367]
Hello,

Please tag a new release with this commit included:
https://github.com/opencontainers/umoci/commit/ea32e1d5e2c1541bca1d2df8025fdb7150d5fb23

Thanks!

**Comment by cyphar** [comment]
Yup, there will be a new release very soon.

**Comment by mateuszkwiatkowski** [comment]
It's included in 0.4.7. Thank you!
