### ISSUE TITLE
Switch to Go 1.13 error types

### ISSUE THREAD

**Issue by cyphar** [opencontainers/umoci#388]
So we don't need to use `github.com/pkg/errors` anymore. Unfortunately this'll mean we can't get stack traces anymore but I don't think that'll be the end of the world.

**Comment by tych0** [comment]
I dunno, I kind of like the stack traces :)

**Comment by cyphar** [comment]
Yeah I do too, the minor issue is that it's not clear to me whether `errors.Is` can reach all the way through both `fmt.Errorf("%w")` wrapping as well as `errors.Wrap` wrapping. On paper it should be able to, since `pkg/errors` got support for Go 1.13 errors but I'm not entirely sure.

The main thing is that we need to switch away from `errors.Cause` because as more libraries switch to Go 1.13 errors it'll become more and more brittle.

**Comment by danishprakash** [comment]
@cyphar do we have a consensus here? I'd like to work on this.
