### ISSUE TITLE
zsh: exec format error: umoci

### ISSUE THREAD

**Issue by finalcreator** [opencontainers/umoci#421]
$ umoci --version                                                                                                                                                                                       
zsh: exec format error: umoci

OS: macOS 12.2.1 21D62 x86_64
 Host: MacBookPro16,1
Kernel: 21.3.0
Terminal Font: CourierNewPS-BoldMT 16
CPU: Intel i9-9880H

**Comment by cyphar** [comment]
We only provide Linux binaries. You'll need to compile umoči for MacOS yourself (though you should be aware that "umoči unpack" currently doesn't work with non-Linux images).
