### ISSUE TITLE
Umoci Not Proccessing org.opencontainers.image.ref.name To OCI Specification

### ISSUE THREAD

**Issue by dejanzelic** [opencontainers/umoci#439]
**Version: `umoci version 0.4.7+ds-2build1`**

I believe that umoci is not properly parsing the tags of an OCI image properly. The [OCI specification states ](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys)that the `org.opencontainers.image.ref.name` variable in the index.json `SHOULD conform to alphanum of A-Za-z0-9 and separator set of -._:@/+`

However, when OCI image contains a full name with the seperator, the name is not parsed. This means that to unpack, we have to specify the full name of the reference rather then just the tag name. Podman, for example, uses the full name of the reference. 

Here is an example of saving alpine in a OCI complaint directory with podman

```
student@container:/tmp/umoci-test$ podman save -o alpine-oci --format oci-dir alpine
Copying blob 24302eb7d908 done  
Copying config a366738a18 done  
Writing manifest to image destination
Storing signatures
```

We can review the index.json and find that `org.opencontainers.image.ref.name` is set to `docker.io/library/alpine:latest` which is, from what I understand, acceptable by the OCI image specification. 

```
student@container:/tmp/umoci-test$ cat alpine-oci/index.json | jq
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:894349dcc3df1aa0b64e6c2f730c293921bafe01df7e0c5e4934e41565366711",
      "size": 348,
      "annotations": {
        "org.opencontainers.image.ref.name": "docker.io/library/alpine:latest"
      }
    }
  ]
}
```

However, when we try to unpack it, we get an error that the tag is not found.

```
student@container:/tmp/umoci-test$ sudo umoci unpack --image alpine-oci bundle
   ⨯ tag is not found: latest 
```

In order to get it to work, we need to specify the full reference name. 

```
student@container:/tmp/umoci-test$ sudo umoci unpack --image alpine-oci:docker.io/library/alpine:latest  bundle
student@container:/tmp/umoci-test$
```

**Comment by cyphar** [comment]
The OCI spec (despite my vocal protests at the time) does not define how `ref.name` should be parsed. The fact that it uses the term "separator" to refer to certain valid characters doesn't really indicate that we should allow submatches. The terminology and valid character set was copied from Docker to ensure compatibility IIRC.

I appreciate that Docker/podman supports this to some degree (though even they wouldn't support resolving "latest" in your example) but umoci is a reference implementation of the image-spec so adding features not defined by the spec is a little bit tricky.

**Comment by dejanzelic** [comment]
Understood! Thank you for the explanation. I will close the issue.
